### PR TITLE
On Subgroup constructor

### PR DESCRIPTION
**Pull request by thinh-le**
@kalmarek I am bumping NPAhierarchy to work with your latest repos. Could you help a bit with the testset below? I also include a small issue with PermutationGroups fyi, which may very well be my mistake as I dont know how to properly coerce a perm to the right parent.

### CODE REVIEW

**Comment by kalmarek** [comment]
@thinh-le thanks for looking into this; I'm not sure though if this really should end up in Groups.jl; It was more of a quick hack back then, and I'm fine for it staying inside your project.

I'd have to think about real design for this (the most general is of course orbit-stabilizer one).
Could you remind me why did we need to store `elts::OrderedSet{GrE}` inside `SubGroup`?

**Comment by thinh-le** [comment]
In NPAhierarchy, we computed stabilizer of a StarAlgebras.AlgebraElement and call Subgroup(; full_set=true). The Subgroup wrapper defined here so that GroupsCore and Action APIs can be used I think.

Edit: the failed coercion test seems to be a problem of AbstractAlgebra.Generic.SymmetricGroup and not of PermutationGroups
```
G = PermutationGroups.SymmetricGroup(4)
g = perm"(1,2)"
gg = G(g)
@test parent(g) != G # passed
@test parent(gg) == G # failed
```

**Comment by kalmarek** [comment]
yeah, this I remember, the question is more of: why was storing the full set necessary?

In that case we had tiny stabilizer inside a huge perm group and this code is not going to work e.g. when you have stabilizer e.g. of index 2 in the supergroup.

**Comment by thinh-le** [comment]
I did not question why we need full set back then but perhaps because I never call the constructor with full_set = false. Also, in case the Subgroup is specify abstractly by generators, the first time one iterate through the whole group we will cache all elements and store order. Edit: probably bad design in case elts is too many.

Btw, do you have facility to specify abstractly stabilizer of an AlgebraElement relative to some ambient symmetry group of Monoid? If such thing exists already, and the resulting object is <:GroupsCore.Group then it will play nice with SymbolicWedderburn.

**Comment by kalmarek** [comment]
yes, I think it's a very specialized usecase and I'd rather not have it in the Groups package. Why can't it stay in the other project of ours?

A way better approach to finding stabilizers were a specifically crafted backtrack search through the Schreier-Sims tree of the group. It should be able to find a generating set for the stabilizer without enumerating all of the elements. Then such a stabilizer object could be designed. I don't have anything like this right now.

**Comment by thinh-le** [comment]
Thanks @kalmarek . And just realized I should have made a pull request inside my fork and tag you.

**Comment by kalmarek** [comment]
I think we should keep this implementation in the NPA project where it is used. What do you think?

**Comment by thinh-le** [comment]
@kalmarek Yes. Also I am writing SignedPermutationGroups and Schreier-Sims as you suggested. Will take some time.

**Comment by kalmarek** [comment]
@thinh-le better not to write those, let's communicate first

**Pull request closed without merging**
